### ISSUE TITLE
Links for Theorem Provers and Program Synthesis are broken

### ISSUE THREAD

**Issue by Chillee** [cs6110/2018sp-web#1]
Meant to file https://github.com/cs6110/2017sp-web/issues/1 in the 2018sp-web repo.

![image](https://user-images.githubusercontent.com/6355099/40465369-661e13b8-5eee-11e8-88fa-d24b523d97fe.png)

Looking in Inspect Element, it shows this:
![image](https://user-images.githubusercontent.com/6355099/40465447-afd9bda4-5eee-11e8-90c5-cd15553f277e.png)

The second `/` in `https://` seems to be missing, causing it to be interpreted as a relative link.

**Comment by sampsyo** [comment]
You're right! Wow; that's weird. It's right in the source, so maybe this is a Metalsmith bug…

**Comment by sampsyo** [comment]
Looks like it was a bug in metalsmith-relative. Should be fixed now. Thanks!
